name: Bug
description: File a bug report
title: "[BUG] <title>"
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      If you need help with installing the theme or installing a client mod, this is not the place to ask.
      Use the client mods respective server to ask.

      Before submitting a bug report, please make sure you have read this *entire* form, and that:
      * You have read the README and it has not answered your question
      * Your bug is not caused by any custom CSS or plugins you have installed.
      * Your issue has not been reported before, [make sure to use the search function!](https://github.com/Slddev/ModernX-Theme/issues)

      **Do not forget to give your issue a descriptive title.** "Bug in the instance screen" makes it hard to distinguish issues at a glance.
- type: dropdown
  attributes:
    label: Client Mod
    description: If you know this bug occurs on multiple client mods, select all you have tested.
    multiple: true
    options:
    - Powercord
    - BetterDiscord
- type: textarea
  attributes:
    label: Description of bug
    description: What did you expect to happen, what happened, and why is it incorrect?
    placeholder: The cat button should show a cat, but it showed a dog instead!
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: A bulleted list, or an exported instance if relevant.
    placeholder: "* Press the cat button"
  validations:
    required: true
- type: textarea
  attributes:
    label: Suspected cause
    description: If you know what could be causing this bug, describe it here.
  validations:
    required: false
- type: textarea
  attributes:
    label: Screenshots
    description: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: This issue is unique
    options:
    - label: I have searched the issue tracker and did not find an issue describing my bug.
      required: true      
