name: Feature Request
description: Suggest an idea for this project
title: "[Feature] <title>"
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      ### Use this form to suggest a feature for ModernX.
- type: input
  attributes:
    label: Suggestion
    description: What do you want ModernX to have?
    placeholder: I want the cat button to meow.
  validations:
    required: true
- type: input
  attributes:
    label: Benefit
    description: Why do you need ModernX to do this?
    placeholder: so that I can always hear a cat when I need to.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: This suggestion is unique
    options:
    - label: I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.
      required: true      
- type: textarea
  attributes:
    label: You may use the editor below to elaborate further.
